# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest
    
steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.3.app/Contents/Developer

    - name: Install xcpretty
      run: gem install xcpretty

    - name: Test project
      run:  xcodebuild -project /Users/runner/work/ToDoList-Swift/ToDoList-Swift.xcodeproj -scheme ToDoList-SwiftTests -destination 'platform=iOS Simulator,OS=17.0,name=iPhone 15' clean build test | xcpretty        
   
