# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.4.app
    - name: Run unit tests
      run: xcodebuild clean test -project "ToDoList-Swift.xcodeproj" -scheme "ToDoList-SwiftTests" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=17.5"
